const BRL = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
const SAVE_KEY='ceo_brasil_v15_save';
const MIN_WAGE=1621;
const money=v=>BRL.format(Math.round(v||0));
const rand=(a,b)=>Math.random()*(b-a)+a;
const chance=p=>Math.random()<p;
const pick=a=>a[Math.floor(Math.random()*a.length)];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const byId=x=>document.getElementById(x);
const img=(path,emoji)=>path?`<div class="imgbox"><img src="${path}" onerror="this.parentElement.outerHTML='<div class=emoji>${emoji}</div>'"></div>`:`<div class="emoji">${emoji}</div>`;

const CITIES=[
{id:'sp',name:'São Paulo',cost:1.28,demand:1.25,security:.82,lux:.55},
{id:'rio',name:'Rio de Janeiro',cost:1.14,demand:1.10,security:.76,lux:.45},
{id:'floripa',name:'Florianópolis',cost:1.18,demand:1.12,security:1.02,lux:.35},
{id:'curitiba',name:'Curitiba',cost:1.00,demand:1.03,security:1.06,lux:.28},
{id:'fortaleza',name:'Fortaleza',cost:.92,demand:1.02,security:.86,lux:.22},
{id:'manaus',name:'Manaus',cost:.92,demand:.95,security:.88,lux:.18},
{id:'brasilia',name:'Brasília',cost:1.12,demand:1.00,security:1.00,lux:.30}
];
const SKILL_NAMES={programacao:'Programação',design:'Design',vendas:'Vendas',gestao:'Gestão',marketing:'Marketing',financas:'Finanças',negociacao:'Negociação',atendimento:'Atendimento',lideranca:'Liderança',juridico:'Jurídico básico'};
const SKILL_KEYS=Object.keys(SKILL_NAMES);
const MILESTONES=[10000,100000,300000,500000,750000,1000000,5000000,10000000,100000000,1000000000,10000000000,100000000000,1000000000000];
const AUDIENCES=['Pessoa física','MEI/autônomo','Comércio local','Empresa pequena','Empresa média','Empresa grande','Governo/licitação','Nacional/internacional'];
const BUSINESS_LEVELS=[
{id:1,name:'Home Office simples',aud:1,desc:'Contratos pequenos e locais.'},
{id:2,name:'Profissional local',aud:2,desc:'Clientes de bairro e MEIs.'},
{id:3,name:'Agência pequena',aud:3,desc:'Pequenas empresas e contratos recorrentes.'},
{id:4,name:'Empresa estruturada',aud:4,desc:'Contratos maiores, sistemas e clientes de outros estados.'},
{id:5,name:'Grupo empresarial',aud:6,desc:'Filiais, licitações e contratos nacionais.'},
{id:6,name:'Magnata nacional',aud:7,desc:'Operações gigantes.'}
];
const SERVICES=[
{id:'arte',name:'Arte para redes sociais',emoji:'🎨',base:350,days:2,diff:.8,audience:0,weights:{design:.65,atendimento:.2,negociacao:.15},risk:.03},
{id:'suporte',name:'Suporte remoto',emoji:'🛠️',base:260,days:1,diff:.7,audience:0,weights:{atendimento:.45,programacao:.25,negociacao:.15,financas:.15},risk:.02},
{id:'landing',name:'Landing page',emoji:'🖥️',base:1200,days:5,diff:1.2,audience:1,weights:{programacao:.35,design:.35,atendimento:.15,negociacao:.15},risk:.06},
{id:'social',name:'Social media mensal',emoji:'📱',base:2200,days:8,diff:1.3,audience:2,weights:{marketing:.45,design:.25,vendas:.15,atendimento:.15},risk:.07,recurring:true},
{id:'loja',name:'Loja virtual',emoji:'🛒',base:8000,days:14,diff:2.1,audience:3,weights:{programacao:.4,design:.2,gestao:.2,atendimento:.1,financas:.1},risk:.14},
{id:'trafego',name:'Campanha de tráfego pago',emoji:'📣',base:6000,days:10,diff:1.8,audience:3,weights:{marketing:.45,vendas:.2,financas:.2,negociacao:.15},risk:.12},
{id:'sistema',name:'Sistema sob medida',emoji:'⚙️',base:30000,days:35,diff:3.4,audience:4,weights:{programacao:.45,gestao:.25,atendimento:.15,negociacao:.1,financas:.05},risk:.22},
{id:'licitacao',name:'Licitação pública de software',emoji:'🏛️',base:120000,days:60,diff:4.4,audience:6,weights:{gestao:.3,juridico:.25,financas:.2,programacao:.15,atendimento:.1},risk:.30},
{id:'nacional',name:'Contrato nacional de tecnologia',emoji:'🌐',base:450000,days:90,diff:5.6,audience:7,weights:{gestao:.3,programacao:.25,lideranca:.2,financas:.15,negociacao:.1},risk:.36}
];
const CLIENT_TYPES=[
{id:'tranquilo',name:'Tranquilo',pay:.98,complain:.65,desc:'Aceita pequenos erros.'},
{id:'exigente',name:'Exigente',pay:1.12,complain:1.35,desc:'Paga melhor, mas reclama fácil.'},
{id:'caloteiro',name:'Caloteiro',pay:.95,complain:1.55,desc:'Procura motivo para pagar menos.'},
{id:'corporativo',name:'Corporativo',pay:1.25,complain:1.2,desc:'Exige nota, prazo e padrão.'},
{id:'apressado',name:'Apressado',pay:1.18,complain:1.4,desc:'Prazo curto.'},
{id:'problematico',name:'Problemático',pay:1.05,complain:2.1,desc:'Risco alto de processo.'}
];
const CLIENTS=['Restaurante do João','Loja da Ana','Mercado Central','Barbearia Rei do Corte','Clínica Vida+','Academia PowerFit','Escola Aprender','Construtora Atlas','E-commerce Bella','Prefeitura local','Startup Nebula','Indústria Vale Norte','Rede de Clínicas Alfa','Grupo Comercial Sul'];
const UPGRADES=[
{id:'notebook',name:'Notebook melhor',emoji:'💻',cost:3500,req:s=>true,effect:'Melhora qualidade técnica e velocidade.'},
{id:'internet',name:'Internet profissional',emoji:'🌐',cost:1800,req:s=>true,effect:'Reduz atraso em trabalhos online.'},
{id:'portfolio',name:'Portfólio profissional',emoji:'📁',cost:2500,req:s=>s.completed>=3,effect:'Libera clientes melhores.'},
{id:'mei',name:'Abrir MEI',emoji:'🧾',cost:500,req:s=>true,effect:'Compra única. Melhora confiança e gera DAS.'},
{id:'contador',name:'Contratar contador',emoji:'📊',cost:1200,req:s=>s.regime!=='informal',effect:'Reduz risco fiscal e alerta limite do MEI.'},
{id:'coworking',name:'Coworking',emoji:'🧑‍💻',cost:2500,req:s=>s.lifetime>=10000,effect:'Aumenta estrutura e networking.'},
{id:'simples',name:'Migrar para Simples',emoji:'🏢',cost:3500,req:s=>s.ownedUpgrades.includes('mei')&&s.lifetime>=20000,effect:'Libera empresas e crescimento.'},
{id:'equipe',name:'Processo seletivo organizado',emoji:'👥',cost:5000,req:s=>s.completed>=8,effect:'Melhora contratação.'},
{id:'juridico',name:'Assessoria jurídica/RH',emoji:'⚖️',cost:6000,req:s=>s.lifetime>=50000,effect:'Reduz custo de processos.'},
{id:'escritorio',name:'Sala comercial',emoji:'🏬',cost:12000,req:s=>s.ownedUpgrades.includes('simples')&&s.employees.length>=1,effect:'Libera empresas médias.'},
{id:'filial',name:'Sistema de filiais',emoji:'🗺️',cost:45000,req:s=>s.lifetime>=500000&&s.ownedUpgrades.includes('escritorio'),effect:'Permite abrir filiais.'}
];
const REGIONAL_HOUSING={
sp:[['sp_paraisopolis','Quarto em Paraisópolis - SP','🏚️',650,55000,8,7,0,.6],['sp_itaquera','Kitnet em Itaquera - SP','🏠',1200,145000,13,3,2,.72],['sp_tatuape','Apartamento no Tatuapé - SP','🏢',3200,520000,22,-2,8,.84],['sp_moema','Apartamento em Moema - SP','🏙️',7200,1300000,30,-6,18,.90],['sp_jardins','Casa nos Jardins - SP','🏰',28000,6200000,44,-11,38,.94]],
rio:[['rio_rocinha','Quarto na Rocinha - RJ','🏚️',600,48000,8,8,0,.55],['rio_cg','Casa simples em Campo Grande - RJ','🏠',1100,150000,13,4,2,.68],['rio_tijuca','Apartamento na Tijuca - RJ','🏢',2800,470000,21,-1,7,.80],['rio_barra','Apartamento na Barra - RJ','🏙️',6500,1200000,29,-5,17,.84],['rio_leblon','Apartamento no Leblon - RJ','🏰',24000,5600000,43,-10,36,.88]],
floripa:[['fl_monte','Quarto no Monte Cristo - Florianópolis','🏚️',700,60000,9,6,0,.70],['fl_centro','Kitnet no Centro - Florianópolis','🏠',1800,260000,16,1,4,.82],['fl_coqueiros','Apartamento em Coqueiros - Florianópolis','🏢',3300,580000,23,-3,9,.88],['fl_campeche','Casa no Campeche - Florianópolis','🏡',5200,980000,28,-6,14,.90],['fl_jurere','Casa em Jurerê Internacional - Florianópolis','🏰',18000,4200000,44,-12,34,.94]],
curitiba:[['ct_sitio','Quarto no Sítio Cercado - Curitiba','🏚️',550,50000,9,5,0,.72],['ct_cic','Kitnet na CIC - Curitiba','🏠',950,120000,14,2,2,.78],['ct_centro','Apartamento no Centro - Curitiba','🏢',2100,360000,21,-2,7,.86],['ct_batel','Apartamento no Batel - Curitiba','🏙️',5500,1050000,30,-7,18,.92]],
fortaleza:[['fo_bomjardim','Quarto no Bom Jardim - Fortaleza','🏚️',450,38000,8,7,0,.58],['fo_messejana','Casa simples na Messejana - Fortaleza','🏠',850,110000,14,3,2,.70],['fo_meireles','Apartamento no Meireles - Fortaleza','🏢',3300,620000,25,-4,12,.86],['fo_aldeota','Apartamento na Aldeota - Fortaleza','🏙️',4700,880000,29,-6,16,.88]],
manaus:[['ma_compensa','Quarto na Compensa - Manaus','🏚️',420,36000,8,7,0,.60],['ma_cidade_nova','Casa na Cidade Nova - Manaus','🏠',850,115000,14,3,2,.72],['ma_adrianopolis','Apartamento em Adrianópolis - Manaus','🏢',3100,600000,25,-4,12,.86]],
brasilia:[['bs_ceilandia','Quarto em Ceilândia - DF','🏚️',700,60000,9,5,0,.70],['bs_samambaia','Casa em Samambaia - DF','🏠',1200,180000,15,2,3,.78],['bs_aguas','Apartamento em Águas Claras - DF','🏢',3000,520000,23,-3,10,.86],['bs_lago','Casa no Lago Sul - DF','🏰',20000,5200000,44,-12,36,.94]]
};
const VEHICLES=[
{id:'bike1',name:'Bicicleta Caloi usada 2018',emoji:'🚲',price:850,year:2018,type:'bicicleta',condition:60,wear:5.5,maint:80,ipva:0,img:''},
{id:'bike2',name:'Bicicleta elétrica usada 2021',emoji:'🚲',price:4200,year:2021,type:'bicicleta',condition:62,wear:5.8,maint:180,ipva:0,img:''},
{id:'pop110',name:'Honda Pop 110i usada 2019',emoji:'🏍️',price:7200,year:2019,type:'moto',condition:58,wear:6.5,maint:220,ipva:.02,img:''},
{id:'biz125',name:'Honda Biz 125 usada 2020',emoji:'🛵',price:10500,year:2020,type:'moto',condition:64,wear:6,maint:260,ipva:.02,img:''},
{id:'cg160',name:'Honda CG 160 Fan usada 2018',emoji:'🏍️',price:12500,year:2018,type:'moto',condition:61,wear:6.4,maint:300,ipva:.02,img:''},
{id:'fazer250',name:'Yamaha Fazer 250 usada 2022',emoji:'🏍️',price:23500,year:2022,type:'moto',condition:72,wear:5.1,maint:520,ipva:.025,img:''},
{id:'gol98',name:'Volkswagen Gol 1.0 usado 1998',emoji:'🚗',price:5000,year:1998,type:'usado',condition:38,wear:9,maint:420,ipva:.02,img:''},
{id:'corsa01',name:'Chevrolet Corsa Sedan usado 2001',emoji:'🚗',price:8000,year:2001,type:'usado',condition:42,wear:8.5,maint:470,ipva:.02,img:''},
{id:'uno04',name:'Fiat Uno Mille usado 2004',emoji:'🚗',price:12000,year:2004,type:'usado',condition:48,wear:8,maint:520,ipva:.02,img:''},
{id:'celta08',name:'Chevrolet Celta usado 2008',emoji:'🚗',price:18000,year:2008,type:'usado',condition:54,wear:7,maint:620,ipva:.025,img:''},
{id:'hb20',name:'Hyundai HB20 usado 2015',emoji:'🚗',price:45000,year:2015,type:'usado',condition:66,wear:5.2,maint:980,ipva:.03,img:''},
{id:'onix',name:'Chevrolet Onix LT usado 2017',emoji:'🚗',price:52000,year:2017,type:'usado',condition:70,wear:4.8,maint:1050,ipva:.03,img:''},
{id:'corolla14',name:'Toyota Corolla XEi usado 2014',emoji:'🚗',price:78000,year:2014,type:'usado',condition:69,wear:4.2,maint:1450,ipva:.035,img:'assets/carro/tayute/Corolla_26_cinza.png'},
{id:'bmw320',name:'BMW 320i usada 2013',emoji:'🚗',price:100000,year:2013,type:'usado',condition:55,wear:7.5,maint:2600,ipva:.04,img:'assets/carro/carro_luxo/bmw-m235i.webp'},
{id:'corolla26',name:'Toyota Corolla 2026',emoji:'🚗',price:165000,year:2026,type:'novo',condition:100,wear:2.8,maint:1700,ipva:.04,img:'assets/carro/tayute/Corolla_26_cinza.png'},
{id:'hilux26',name:'Toyota Hilux 2026',emoji:'🛻',price:330000,year:2026,type:'novo',condition:100,wear:3.1,maint:3100,ipva:.04,img:'assets/carro/tayute/hilux_cabine_dupla_26.png'},
{id:'golfgti',name:'Volkswagen Golf GTI 2026',emoji:'🚗',price:390000,year:2026,type:'novo',condition:100,wear:3.0,maint:3600,ipva:.04,img:'assets/carro/volksbagis/Golf_GTI.webp'},
{id:'m3',name:'BMW M3 Competition',emoji:'🏎️',price:754000,year:2025,type:'luxo',condition:100,wear:4.2,maint:9500,ipva:.04,img:'assets/carro/carro_luxo/bmw-m3.webp'},
{id:'rs6',name:'Audi RS6 Avant',emoji:'🏎️',price:1250000,year:2026,type:'luxo',condition:100,wear:4.4,maint:15000,ipva:.04,img:'assets/carro/carro_luxo/audi-rs6.webp'},
{id:'porsche911',name:'Porsche 911 Carrera',emoji:'🏎️',price:980000,year:2026,type:'luxo',condition:100,wear:4.0,maint:14000,ipva:.04,img:'assets/carro/proshi/911_carrera_t_26.jpg'},
{id:'ferrari296',name:'Ferrari 296 GTB',emoji:'🏎️',price:4300000,year:2025,type:'superluxo',condition:100,wear:5.0,maint:42000,ipva:.04,img:'assets/carro/carro_luxo/ferrari_296.webp'},
{id:'urus',name:'Lamborghini Urus',emoji:'🚙',price:3600000,year:2025,type:'superluxo',condition:100,wear:5.2,maint:39000,ipva:.04,img:'assets/carro/carro_luxo/urus_25.webp'}
];
const FOOD={marmita:{name:'Marmita simples',cost:18,hunger:26,energy:3,stress:0},mercado:{name:'Comprar comida no mercado',cost:120,hunger:65,energy:-3,stress:-1},restaurante:{name:'Ir ao restaurante',cost:55,hunger:45,energy:-8,stress:-7},ifood:{name:'Pedir iFood + frete',cost:42,hunger:35,energy:0,stress:-2},churrasco:{name:'Churrascaria/rodízio',cost:140,hunger:75,energy:-5,stress:-12}};
const ROUTINE={trabalhar:{name:'Trabalhar',energy:-8,hunger:-8,stress:5,motivation:-1},estudar:{name:'Estudar',energy:-5,hunger:-5,stress:2,motivation:2},vender:{name:'Fazer propaganda',energy:-7,hunger:-6,stress:4,motivation:1},burocracia:{name:'Resolver burocracia',energy:-4,hunger:-3,stress:3,motivation:0},descansar:{name:'Descansar',energy:14,hunger:-3,stress:-8,motivation:2},familia:{name:'Família/lazer',energy:5,hunger:-5,stress:-10,motivation:5},dormir:{name:'Dormir cedo',energy:20,hunger:-4,stress:-8,motivation:1}};
const COURSES=SKILL_KEYS.map((k,i)=>({id:k,name:`Curso de ${SKILL_NAMES[k]}`,skill:k,cost:500+i*120,xp:45,energy:12}));
const BRANCHES=[
{id:'sp',name:'São Paulo',cost:80000,monthly:12000,desc:'Demanda alta e concorrência alta.'},
{id:'rio',name:'Rio de Janeiro',cost:60000,monthly:9000,desc:'Mídia, turismo e risco maior.'},
{id:'floripa',name:'Florianópolis',cost:52000,monthly:7600,desc:'Tecnologia, startups e SaaS.'},
{id:'manaus',name:'Manaus',cost:45000,monthly:6500,desc:'Indústria e logística.'},
{id:'fortaleza',name:'Fortaleza',cost:42000,monthly:6200,desc:'Turismo, comércio e social media.'},
{id:'brasilia',name:'Brasília',cost:70000,monthly:10000,desc:'Licitações e consultoria.'}
];
const COMPETITORS=['Agência Barata','Studio Premium','Freelancer Local','Empresa Grande'];
const TABS=[['dashboard','📌 Painel'],['routine','🗓️ Rotina'],['contracts','💼 Contratos'],['recurring','🔁 Recorrentes'],['status','⭐ Status'],['courses','🎓 Cursos'],['upgrades','🌳 Upgrades'],['team','👷 Equipe'],['legal','⚖️ Jurídico'],['bills','🧾 Cobranças'],['bank','🏦 Banco'],['calendar','📅 Agenda'],['food','🍽️ Alimentação'],['housing','🏠 Moradia'],['cars','🚗 Veículos'],['branches','🗺️ Filiais'],['dre','📊 DRE']];
let state, currentTab='dashboard', timer=null, speed=1500;
function city(){return CITIES.find(c=>c.id===state.city)||CITIES[0]}
function housingOptions(){return (REGIONAL_HOUSING[state.city]||REGIONAL_HOUSING.sp).map(a=>({id:a[0],name:a[1],emoji:a[2],rent:a[3],buy:a[4],energy:a[5],stress:a[6],status:a[7],security:a[8]}))}
function home(){return housingOptions().find(h=>h.id===state.housing)||housingOptions()[0]}
function skillValue(skills,k){const s=skills?.[k]||{level:1,xp:0};return (s.level||1)+(s.xp||0)/100}
function biz(){return BUSINESS_LEVELS.find(b=>b.id===state.businessLevel)||BUSINESS_LEVELS[0]}
function initSkills(){const o={};SKILL_KEYS.forEach(k=>o[k]={level:1,xp:0});return o}
function defaultState(){return {started:false,player:'Empreendedor',company:'Garagem Digital',gender:'homem',age:18,city:'sp',cash:5000,day:1,month:1,year:1,energy:100,hunger:82,health:100,stress:12,motivation:82,rep:42,score:520,clientRep:42,bankRep:520,fiscalRisk:10,regime:'informal',ownedUpgrades:[],businessLevel:1,skills:initSkills(),completed:0,lifetime:0,monthRevenue:0,monthExpenses:0,foodSpent:0,contracts:[],jobs:[],recurringClients:[],employees:[],candidates:[],candidateExpiresDay:3,nextContractAt:4,totalDays:1,bills:[],legalCases:[],loans:[],carShop:[],ownedVehicles:[],currentVehicle:null,branches:[],housing:'sp_paraisopolis',housingMode:'rent',ownedHomes:[],relationship:'solteiro',children:0,routine:{morning:'trabalhar',afternoon:'trabalhar',night:'dormir'},competitors:COMPETITORS.map(n=>({name:n,power:35})),log:[],news:[],reached:[]}}
function initSelects(){byId('startCity').innerHTML=CITIES.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}
function openModal(id){byId(id).classList.add('show')} function closeModal(id){byId(id).classList.remove('show')}
function addLog(msg,type=''){state.log.unshift({msg:`Dia ${state.day}, Mês ${state.month}: ${msg}`,type});state.log=state.log.slice(0,80);renderLog()}
function startGame(){state=defaultState();state.player=byId('startName').value||'Empresário';state.company=byId('startCompany').value||'Garagem Digital';state.gender=byId('startGender').value;state.age=clamp(Number(byId('startAge').value)||18,18,60);state.city=byId('startCity').value;state.housing=housingOptions()[0].id;const focus=byId('startFocus').value;state.skills[focus].level=2;state.skills.atendimento.level=2;state.started=true;closeModal('startModal');generateContracts(4);if(typeof scheduleNextContract==='function') scheduleNextContract();refreshCandidates();refreshCarShop();addLog(`Você começou a ${state.company} em home office, morando em ${home().name}, com ${money(5000)}.`,'good');renderAll()}
function renderTabs(){byId('tabs').innerHTML=TABS.map(([k,l])=>`<button class="tab ${currentTab===k?'active':''}" onclick="currentTab='${k}';renderAll()">${l}</button>`).join('')}
function renderAll(){try{renderHud();renderTabs();renderContent();renderLeft();renderLog()}catch(e){console.error(e);byId('content').innerHTML=`<div class="card"><h2>Erro na tela</h2><p>${e.message}</p></div>`}}
function renderHud(){byId('cash').textContent=money(state.cash);byId('date').textContent=`Dia ${state.day} / Mês ${state.month} / Ano ${state.year}`;byId('lifetime').textContent=money(state.lifetime);byId('bizLevel').textContent=biz().name;byId('rep').textContent=Math.round(state.rep);byId('score').textContent=Math.round(state.score)}
function renderLeft(){byId('avatar').textContent=state.gender==='mulher'?'👩‍💼':'👨‍💼';byId('playerLabel').textContent=`${state.player} · ${state.company}`;byId('lifeLabel').textContent=`${state.age} anos · ${state.relationship} · ${city().name}`;[['energy',state.energy],['hunger',state.hunger],['health',state.health],['stress',state.stress],['motivation',state.motivation]].forEach(([k,v])=>{byId(k+'Label').textContent=`${Math.round(v)}%`;byId(k+'Bar').style.width=`${clamp(v,0,100)}%`});const h=home();byId('currentHousing').innerHTML=`<b>${h.name}</b><p class="muted">${state.housingMode==='own'?'Própria':'Alugada'} · ${money(h.rent*city().cost)}/mês</p>`;byId('currentFood').innerHTML=`<b>${state.hunger>70?'Bem alimentado':state.hunger>35?'Com fome':'Passando fome'}</b><p class="muted">Comida no mês: ${money(state.foodSpent)}</p><button onclick="currentTab='food';renderAll()">Comprar comida</button>`;const v=state.ownedVehicles.find(x=>x.ownedId===state.currentVehicle);byId('currentVehicle').innerHTML=v?`<b>${v.name}</b><p class="muted">Condição ${Math.round(v.condition)}%</p><button onclick="maintainVehicle()">Manutenção</button>`:'<p class="muted">Sem veículo.</p>';byId('milestones').innerHTML=MILESTONES.slice(0,9).map(m=>`<div class="mini-card"><b>${money(m)}</b><p class="muted">${state.reached.includes(m)?'✅ atingido':'Faturamento total'}</p></div>`).join('')}
function renderLog(){if(!state)return;byId('log').innerHTML=state.log.map(e=>`<div class="event ${e.type}">${e.msg}</div>`).join('')||'<p class="muted">Diário vazio.</p>';byId('news').innerHTML=state.news.map(n=>`<div class="event warn">${n}</div>`).join('')}
function renderContent(){const map={dashboard,routine,contracts,recurring,status,courses,upgrades,team,legal,bills,bank,calendar,food,housing,cars,branches,dre};byId('content').innerHTML=(map[currentTab]||dashboard)()}
function addSkillXp(k,xp){const s=state.skills[k];if(!s)return;s.xp+=xp;while(s.xp>=100){s.xp-=100;s.level++;addLog(`${SKILL_NAMES[k]} subiu para nível ${s.level}.`,'good')}}
function weightedSkill(c,executor='player'){let source=state.skills;if(executor!=='player'){const e=state.employees.find(x=>x.id===executor);if(e)source=e.skills}let total=0;Object.entries(c.weights).forEach(([k,w])=>total+=skillValue(source,k)*w);return total}
function recalcBusinessLevel(){let lvl=1;if(state.lifetime>=10000&&state.completed>=5&&state.ownedUpgrades.includes('notebook'))lvl=2;if(state.lifetime>=100000&&state.regime!=='informal'&&state.employees.length>=1&&state.ownedUpgrades.includes('coworking'))lvl=3;if(state.lifetime>=500000&&state.ownedUpgrades.includes('contador')&&state.rep>=55)lvl=4;if(state.lifetime>=5000000&&state.branches.length&&state.ownedUpgrades.includes('juridico'))lvl=5;if(state.lifetime>=1000000000)lvl=6;state.businessLevel=Math.max(state.businessLevel,lvl)}
function availableServices(){const aud=biz().aud;return SERVICES.filter(s=>s.audience<=aud+1)}
function generateContracts(n=2){for(let i=0;i<n;i++){const s=pick(availableServices());const clientType=pick(CLIENT_TYPES);const value=s.base*city().demand*clientType.pay*rand(.82,1.28)*(1+state.branches.length*.08);state.contracts.push({id:uid(),client:pick(CLIENTS),clientType:clientType.name,service:s.name,emoji:s.emoji,serviceId:s.id,value,days:Math.max(1,Math.round(s.days*rand(.75,1.3))),remaining:0,progress:0,diff:s.diff,audience:s.audience,weights:s.weights,risk:s.risk*clientType.complain,expires:Math.ceil(rand(3,8)),recurring:!!s.recurring,status:'Disponível'})}}
function contractCard(c){const req=Object.entries(c.weights).map(([k,w])=>`${SKILL_NAMES[k]} ${Math.ceil(c.diff*w)}`).join(' · ');return `<div class="card"><h4>${c.emoji} ${c.service}</h4><p><b>${c.client}</b> · ${c.clientType}</p><div class="pills"><span class="pill">Valor ${money(c.value)}</span><span class="pill">Prazo ${c.days}d</span><span class="pill">Expira ${c.expires}d</span><span class="pill">${AUDIENCES[c.audience]}</span></div><p class="muted small">Recomendado: ${req}</p><div class="mini-actions"><b>Preço:</b><button onclick="tryContract('${c.id}','player',.85)">Baixo</button><button class="primary" onclick="tryContract('${c.id}','player',1)">Justo</button><button onclick="tryContract('${c.id}','player',1.25)">Alto</button></div><div class="actions-row"><button onclick="chooseExecutor('${c.id}')">Delegar</button><button class="danger" onclick="rejectContract('${c.id}')">Recusar</button></div></div>`}
function chooseExecutor(id){const c=state.contracts.find(x=>x.id===id);if(!c)return;let html=`<h2>Quem executa?</h2><p>${c.service} para ${c.client}</p><div class="stack"><button class="primary" onclick="tryContract('${id}','player',1);closeModal('interviewModal')">Você</button>`;state.employees.forEach(e=>html+=`<button onclick="tryContract('${id}','${e.id}',1);closeModal('interviewModal')">${e.name} · ${e.label}</button>`);html+=`</div><button onclick="closeModal('interviewModal')">Cancelar</button>`;byId('interviewBox').innerHTML=html;openModal('interviewModal')}
function tryContract(id,executor,priceMult){const c=state.contracts.find(x=>x.id===id);if(!c)return;const closeChance=.75 + skillValue(state.skills,'negociacao')*.035 - (priceMult-1)*.75 + (priceMult<1?.18:0);if(!chance(clamp(closeChance,.12,.98))){state.contracts=state.contracts.filter(x=>x.id!==id);pick(state.competitors).power+=1;addLog(`${c.client} recusou sua proposta de ${money(c.value*priceMult)}. Um concorrente pode pegar.`, 'warn');return renderAll()}acceptContract(id,executor,priceMult)}
function acceptContract(id,executor='player',priceMult=1){const c=state.contracts.find(x=>x.id===id);if(!c)return;c.value*=priceMult;c.status='Em execução';c.remaining=c.days;c.progress=0;c.executor=executor;state.jobs.push(c);state.contracts=state.contracts.filter(x=>x.id!==id);if(executor==='player')state.energy=clamp(state.energy-8,0,100);addLog(`Contrato aceito: ${c.service} para ${c.client}.`, 'good');renderAll()}
function rejectContract(id){const c=state.contracts.find(x=>x.id===id);if(!c)return;state.contracts=state.contracts.filter(x=>x.id!==id);state.rep=clamp(state.rep-.3,0,100);pick(state.competitors).power+=.6;addLog(`Você recusou a proposta de ${c.client}: ${c.service}.`, 'warn');renderAll()}
function updateJobDay(j){const count=state.jobs.filter(x=>x.executor===j.executor).length;const skill=weightedSkill(j,j.executor);let speed=(skill/j.diff)*8/(count||1);if(j.executor==='player'){speed*=state.energy<35?.65:1;speed*=state.hunger<35?.70:1;speed*=state.stress>75?.75:1}speed*=state.ownedUpgrades.includes('notebook')?1.12:1;speed*=state.ownedUpgrades.includes('internet')?1.08:1;j.progress=clamp(j.progress+rand(speed*.65,speed*1.35),0,100);j.remaining--;if(j.remaining<0)j.status='Atrasado'}
function finishJob(j){const skill=weightedSkill(j,j.executor);let quality=50+(skill-j.diff)*18+rand(-12,18);if(j.remaining<0)quality+=j.remaining*6;if(j.executor==='player'){quality+=(state.health-70)*.18+(state.motivation-60)*.12-(100-state.hunger)*.12-state.stress*.10}quality=clamp(quality,0,100);let payPct=quality>=90?1.08:quality>=70?1:quality>=50?.72:quality>=30?.45:.12;if(chance(j.risk*(quality<60?2.2:1)))payPct*=rand(.45,.85);const paid=j.value*payPct;state.cash+=paid;state.monthRevenue+=paid;state.lifetime+=paid;state.completed++;Object.keys(j.weights).forEach(k=>addSkillXp(k,Math.max(3,12*j.weights[k])));if(quality>=70){state.rep=clamp(state.rep+1.5,0,100);state.clientRep=clamp(state.clientRep+1.5,0,100);addLog(`Cliente avaliou ${j.service}: ${Math.round(quality)}/100. Recebido ${money(paid)}.`, 'good');if(j.recurring&&quality>82&&chance(.45))addRecurring(j,quality)}else{state.rep=clamp(state.rep-2.5,0,100);state.clientRep=clamp(state.clientRep-3,0,100);addLog(`Serviço mal avaliado (${Math.round(quality)}/100). Cliente pagou só ${money(paid)}.`, 'bad');if(quality<45&&chance(j.risk*2.4))createClientCase(j,quality)}}
function addRecurring(j,q){const monthly=Math.max(280,j.value*rand(.10,.22));state.recurringClients.push({id:uid(),client:j.client,service:j.service,monthly,quality:Math.round(q),months:0,churn:.04+(100-q)/300});addLog(`${j.client} virou cliente recorrente: ${money(monthly)}/mês.`, 'good')}
function createClientCase(j,quality){const amount=j.value*rand(.8,2.4);state.legalCases.push({id:uid(),kind:'Cliente',name:j.client,reason:`Serviço mal feito: ${j.service} (${Math.round(quality)}/100)`,requested:amount,risk:clamp(.45+(60-quality)/100,0,1),status:'Notificação',days:10,costs:0});addLog(`${j.client} iniciou reclamação/processo pedindo ${money(amount)}.`, 'bad')}
function createLaborCase(e){if(state.legalCases.some(c=>c.employeeId===e.id&&c.status!=='Encerrado'))return;state.legalCases.push({id:uid(),kind:'Trabalhista',employeeId:e.id,name:e.name,reason:'Salários/obrigações atrasadas',requested:e.salary*rand(4,9),risk:state.ownedUpgrades.includes('juridico')?.42:.68,status:'Notificação',days:10,costs:0});addLog(`${e.name} abriu reclamação trabalhista.`, 'bad')}
function createFiscalCase(b){state.legalCases.push({id:uid(),kind:'Fiscal',name:'Receita/Prefeitura',reason:`Imposto não pago: ${b.name}`,requested:b.amount*rand(1.5,3.5),risk:state.ownedUpgrades.includes('contador')?.35:.62,status:'Notificação',days:15,costs:0});addLog(`Você recebeu notificação fiscal por ${b.name}.`, 'bad')}
function updateLegalDay(c){if(['Acordo','Vencido','Encerrado'].includes(c.status))return;c.days--;if(c.days<=0){const lost=chance(c.risk);if(lost){const total=c.requested*(1+rand(.05,.45))+c.costs;state.cash-=total;state.monthExpenses+=total;c.status='Perdido';state.rep=clamp(state.rep-4,0,100);addLog(`Você perdeu caso ${c.name}. Pagou ${money(total)}.`, 'bad')}else{c.status='Vencido';state.rep=clamp(state.rep+1,0,100);addLog(`Você venceu/encerrou o caso de ${c.name}.`, 'good')}}}
function settleCase(id){const c=state.legalCases.find(x=>x.id===id);if(!c)return;const total=c.requested*(state.ownedUpgrades.includes('juridico')?.38:.55);if(state.cash<total)return addLog('Caixa insuficiente para acordo.', 'bad');state.cash-=total;state.monthExpenses+=total;c.status='Acordo';state.rep=clamp(state.rep-1.5,0,100);addLog(`Acordo com ${c.name} por ${money(total)}.`, 'warn');renderAll()}
function defendCase(id){const c=state.legalCases.find(x=>x.id===id);if(!c)return;const cost=(state.ownedUpgrades.includes('juridico')?900:2800)*rand(.8,1.4);if(state.cash<cost)return addLog('Sem caixa para defesa.', 'bad');state.cash-=cost;c.costs+=cost;c.status='Defesa em andamento';c.days=Math.ceil(rand(30,75));c.risk=clamp(c.risk-(skillValue(state.skills,'juridico')*.03),.1,.9);addLog(`Você decidiu recorrer. Custo inicial: ${money(cost)}.`, 'warn');renderAll()}
function ignoreCase(id){const c=state.legalCases.find(x=>x.id===id);if(!c)return;c.status='Ignorado';c.risk=clamp(c.risk+.25,0,1);state.rep=clamp(state.rep-3,0,100);addLog(`Você ignorou o caso de ${c.name}. Risco aumentou.`, 'bad');renderAll()}
function buyUpgrade(id){const u=UPGRADES.find(x=>x.id===id);if(!u)return;if(state.ownedUpgrades.includes(id))return addLog(`${u.name} já foi comprado.`, 'warn');if(!u.req(state))return addLog(`Requisitos ainda não atendidos para ${u.name}.`, 'bad');if(state.cash<u.cost)return addLog(`Falta dinheiro para ${u.name}.`, 'bad');state.cash-=u.cost;state.monthExpenses+=u.cost;state.ownedUpgrades.push(id);if(id==='mei')state.regime='mei';if(id==='simples')state.regime='simples';state.rep=clamp(state.rep+(id==='portfolio'?3:1),0,100);addLog(`Upgrade comprado: ${u.name}.`, 'good');recalcBusinessLevel();renderAll()}
function refreshCandidates(){const cargos=[['Estagiário',MIN_WAGE*.65,.55],['Júnior',MIN_WAGE*1.5,1.1],['Pleno',MIN_WAGE*3,2.2],['Sênior',MIN_WAGE*5,3.4],['Vendedor',MIN_WAGE*1.4,1.5],['Gerente',MIN_WAGE*7,3.0],['Contador',MIN_WAGE*4,2.2],['Advogado',MIN_WAGE*6,2.6]];const names=['Lucas','Amanda','Rafael','Bianca','João','Carla','Diego','Marina','Pedro','Aline','Bruno','Gabi'];state.candidates=[];for(let i=0;i<5;i++){const [label,base,skillBase]=pick(cargos);const skills=initSkills();SKILL_KEYS.forEach(k=>skills[k].level=Math.max(1,Math.round(rand(.6,skillBase))));if(label==='Vendedor')skills.vendas.level+=2;if(label==='Contador')skills.financas.level+=2;if(label==='Advogado')skills.juridico.level+=2;state.candidates.push({id:uid(),name:pick(names),age:Math.round(rand(18,46)),label,salary:base*city().cost*rand(.9,1.25),skills,personality:pick(['comunicativo','quieto','ambicioso','aprendiz','exigente','focado']),experience:Math.round(rand(0,8)),morale:70,active:true,monthsLate:0,task:'ocioso',accept:rand(.50,.88)})}state.candidateExpiresDay=state.day+3;addLog('Novos candidatos apareceram. Você tem 3 dias para contratar.', 'good')}
function interviewCandidate(id){const c=state.candidates.find(x=>x.id===id);if(!c)return;const best=SKILL_KEYS.sort((a,b)=>skillValue(c.skills,b)-skillValue(c.skills,a)).slice(0,3).map(k=>`${SKILL_NAMES[k]} ${Math.round(skillValue(c.skills,k))}`).join(' · ');byId('interviewBox').innerHTML=`<h2>Entrevista: ${c.name}</h2><p>${c.age} anos · ${c.label} · ${c.personality}</p><p>Pretensão: <b>${money(c.salary)}/mês</b></p><p class="muted">Pontos fortes: ${best}</p><p>“Quero crescer, mas preciso sentir segurança na empresa e receber em dia.”</p><div class="actions-row"><button onclick="hireCandidate('${c.id}',.9)">Oferecer ${money(c.salary*.9)}</button><button class="primary" onclick="hireCandidate('${c.id}',1)">Oferecer ${money(c.salary)}</button><button onclick="hireCandidate('${c.id}',1.2)">Oferecer ${money(c.salary*1.2)}</button><button class="danger" onclick="closeModal('interviewModal')">Rejeitar</button></div>`;openModal('interviewModal')}
function hireCandidate(id,mult){const c=state.candidates.find(x=>x.id===id);if(!c)return;const offer=c.salary*mult;const accepted=chance(c.accept+(mult-1)*.9-(state.rep<35?.25:0));if(!accepted){addLog(`${c.name} recusou a proposta de ${money(offer)}.`, 'bad');closeModal('interviewModal');return}state.employees.push({...c,salary:offer});state.candidates=state.candidates.filter(x=>x.id!==id);addLog(`${c.name} foi contratado como ${c.label} por ${money(offer)}/mês.`, 'good');closeModal('interviewModal');recalcBusinessLevel();renderAll()}
function setEmployeeTask(id,task){const e=state.employees.find(x=>x.id===id);if(!e)return;e.task=task;addLog(`${e.name} agora está em tarefa: ${task}.`, 'good');renderAll()}
function fireEmployee(id){const e=state.employees.find(x=>x.id===id);if(!e)return;const cost=e.salary*.8;if(state.cash<cost)return addLog('Sem caixa para rescisão simulada.', 'bad');state.cash-=cost;state.employees=state.employees.filter(x=>x.id!==id);addLog(`${e.name} foi desligado. Rescisão: ${money(cost)}.`, 'warn');renderAll()}
function processEmployeeTasks(){state.employees.forEach(e=>{if(e.task==='vender'&&chance(.20+skillValue(e.skills,'vendas')*.035)){generateContracts(1);addLog(`${e.name} trouxe nova oportunidade.`, 'good')}if(e.task==='treinar'&&chance(.45)){const k=pick(SKILL_KEYS);e.skills[k].xp+=8;while(e.skills[k].xp>=100){e.skills[k].xp-=100;e.skills[k].level++}}if(e.task==='atender')state.rep=clamp(state.rep+.05,0,100)})}
function refreshCarShop(){let pool=VEHICLES.filter(v=>['bicicleta','moto','usado','novo'].includes(v.type));if(state.cash>120000||city().lux>.3)pool=pool.concat(VEHICLES.filter(v=>v.type==='luxo'));if(state.cash>1200000||city().lux>.45)pool=pool.concat(VEHICLES.filter(v=>v.type==='superluxo'));state.carShop=[];for(let i=0;i<8;i++){const v={...pick(pool),offerId:uid()};v.price*=rand(.92,1.08);v.condition=clamp((v.condition||100)+rand(-7,4),20,100);state.carShop.push(v)}addLog('Loja de veículos atualizada: novas ofertas do mês.', 'good')}
function buyVehicle(offerId){const v=state.carShop.find(x=>x.offerId===offerId);if(!v)return;if(state.cash<v.price)return addLog('Caixa insuficiente para comprar esse veículo.', 'bad');state.cash-=v.price;const owned={...v,ownedId:uid()};state.ownedVehicles.push(owned);state.currentVehicle=owned.ownedId;addLog(`Você comprou ${v.name} por ${money(v.price)}.`, 'good');renderAll()}
function maintainVehicle(){const v=state.ownedVehicles.find(x=>x.ownedId===state.currentVehicle);if(!v)return;const cost=v.maint*rand(1.5,3.2);if(state.cash<cost)return addLog('Sem caixa para manutenção.', 'bad');state.cash-=cost;state.monthExpenses+=cost;v.condition=clamp(v.condition+rand(25,45),0,100);addLog(`Manutenção feita em ${v.name}: ${money(cost)}.`, 'good');renderAll()}
function monthlyVehicleWear(){state.ownedVehicles.slice().forEach(v=>{v.condition-=v.wear*rand(.75,1.35);if(v.condition<25&&chance(.22)){addLog(`${v.name} quebrou feio e deu PT. Você perdeu o veículo.`, 'bad');state.ownedVehicles=state.ownedVehicles.filter(x=>x.ownedId!==v.ownedId);if(state.currentVehicle===v.ownedId)state.currentVehicle=null}else if(v.condition<45&&chance(.35))addLog(`${v.name} está em péssima condição. Faça manutenção ou pode dar PT.`, 'warn')})}
function eat(kind){const f=FOOD[kind];const cost=f.cost*city().cost;if(state.cash<cost)return addLog('Sem caixa para essa alimentação.', 'bad');state.cash-=cost;state.monthExpenses+=cost;state.foodSpent+=cost;state.hunger=clamp(state.hunger+f.hunger,0,100);state.energy=clamp(state.energy+f.energy,0,100);state.stress=clamp(state.stress+f.stress,0,100);if(kind==='churrasco')state.motivation=clamp(state.motivation+5,0,100);addLog(`${f.name}: ${money(cost)}. Fome ${Math.round(state.hunger)}%.`, 'good');renderAll()}
function rentHousing(id){const h=housingOptions().find(x=>x.id===id);if(!h)return;if(state.housing===id&&state.housingMode==='rent')return addLog('Você já mora nesse aluguel.', 'warn');const cost=Math.max(150,h.rent*city().cost*.45);if(state.cash<cost)return addLog('Sem caixa para mudança/caução.', 'bad');state.cash-=cost;state.monthExpenses+=cost;state.housing=id;state.housingMode='rent';addLog(`Você alugou: ${h.name}.`, 'good');renderAll()}
function buyHousing(id){const h=housingOptions().find(x=>x.id===id);if(!h)return;if(state.ownedHomes.includes(id)){state.housing=id;state.housingMode='own';addLog(`Você se mudou para seu imóvel: ${h.name}.`, 'good');return renderAll()}const cost=h.buy*city().cost;if(state.cash<cost)return addLog(`Caixa insuficiente para comprar ${h.name}.`, 'bad');state.cash-=cost;state.monthExpenses+=cost;state.ownedHomes.push(id);state.housing=id;state.housingMode='own';addLog(`Você comprou ${h.name} por ${money(cost)}.`, 'good');renderAll()}
function sellHousing(id){const h=housingOptions().find(x=>x.id===id);if(!h||!state.ownedHomes.includes(id))return;const value=h.buy*city().cost*rand(.78,.92);state.cash+=value;state.ownedHomes=state.ownedHomes.filter(x=>x!==id);if(state.housing===id){state.housing=housingOptions()[0].id;state.housingMode='rent'}addLog(`Você vendeu ${h.name} por ${money(value)}.`, 'warn');renderAll()}
function requestLoan(){const amount=Number(byId('loanAmount')?.value||0);const months=Number(byId('loanMonths')?.value||12);const purpose=byId('loanPurpose')?.value||'capital de giro';if(amount<500)return addLog('Digite um valor válido.', 'bad');const debt=state.loans.reduce((s,l)=>s+l.balance,0);const avg=Math.max(1,state.lifetime/Math.max(1,(state.year-1)*12+state.month));let a=state.score+(state.regime==='informal'?-90:70)+Math.min(140,avg/700)+Math.min(120,netWorth()/10000)-debt/1200-amount/2500+(state.ownedUpgrades.includes('contador')?35:0);let approved=0,result='Reprovado';if(a>650){approved=amount;result='Aprovado'}else if(a>520){approved=amount*rand(.55,.85);result='Aprovado parcialmente'}else if(a>430){approved=amount*rand(.25,.5);result='Aprovado com juros alto'}if(approved<500)return addLog(`Banco reprovou pedido de ${money(amount)}. Score/receita/patrimônio insuficientes.`, 'bad');const rate=clamp(.018+(650-a)/9000+(state.regime==='informal'?.018:0),.016,.075);const payment=approved*(rate*Math.pow(1+rate,months))/(Math.pow(1+rate,months)-1);state.cash+=approved;state.loans.push({id:uid(),amount:approved,balance:approved,monthsLeft:months,rate,payment,purpose});state.score-=approved/20000;addLog(`${result}: pedido ${money(amount)}, liberado ${money(approved)}. ${months}x de ${money(payment)}.`, result==='Aprovado'?'good':'warn');renderAll()}
function addBill(type,name,amount,meta={}){state.bills.push({id:uid(),type,name,amount,status:'Pendente',meta})}
function generateMonthlyBills(){const h=home();addBill('moradia',`${state.housingMode==='rent'?'Aluguel':'Condomínio/manutenção'} - ${h.name}`,(state.housingMode==='rent'?h.rent:h.buy*.0012)*city().cost+state.children*450,{housingId:h.id});if(state.regime==='mei')addBill('imposto','DAS MEI',78,{});if(state.regime==='simples')addBill('imposto','Imposto Simples Nacional',Math.max(120,state.monthRevenue*.06),{});state.employees.forEach(e=>addBill('salario',`Salário de ${e.name}`,e.salary*1.32,{employeeId:e.id}));state.loans.forEach(l=>addBill('banco',`Parcela banco - ${l.purpose}`,l.payment,{loanId:l.id}));state.branches.forEach(b=>addBill('filial',`Custo filial ${b.name}`,b.monthly,{branchId:b.id}));state.ownedVehicles.forEach(v=>{addBill('carro',`Seguro/IPVA/licenciamento - ${v.name}`,v.price*v.ipva/12+v.maint*.35,{vehicleId:v.ownedId});if(v.condition<65)addBill('manutencao',`Manutenção recomendada - ${v.name}`,v.maint*rand(.8,1.8),{vehicleId:v.ownedId})});if(state.ownedUpgrades.includes('contador'))addBill('contador','Honorários do contador',650,{});if(state.ownedUpgrades.includes('juridico'))addBill('juridico','Assessoria jurídica/RH',1200,{})}
function payBill(id){const b=state.bills.find(x=>x.id===id);if(!b||b.status!=='Pendente')return;if(state.cash<b.amount)return addLog('Caixa insuficiente para pagar.', 'bad');state.cash-=b.amount;state.monthExpenses+=b.amount;b.status='Pago';if(b.type==='banco'){const l=state.loans.find(x=>x.id===b.meta.loanId);if(l){l.balance-=Math.max(0,l.payment-l.balance*l.rate);l.monthsLeft--;if(l.monthsLeft<=0||l.balance<=10)state.loans=state.loans.filter(x=>x.id!==l.id)}}if(b.type==='salario'){const e=state.employees.find(x=>x.id===b.meta.employeeId);if(e){e.monthsLate=0;e.morale=clamp(e.morale+4,0,100)}}if(b.type==='manutencao'){const v=state.ownedVehicles.find(x=>x.ownedId===b.meta.vehicleId);if(v)v.condition=clamp(v.condition+rand(15,35),0,100)}addLog(`Cobrança paga: ${b.name}.`, 'good');renderAll()}
function delayBill(id){const b=state.bills.find(x=>x.id===id);if(!b||b.status!=='Pendente')return;b.status='Atrasado';state.score-=b.type==='banco'?18:4;state.stress+=3;if(b.type==='salario'){const e=state.employees.find(x=>x.id===b.meta.employeeId);if(e){e.monthsLate=(e.monthsLate||0)+1;e.morale-=18;if(e.monthsLate>=3)createLaborCase(e)}}if(b.type==='manutencao'){const v=state.ownedVehicles.find(x=>x.ownedId===b.meta.vehicleId);if(v)v.condition-=8}addLog(`Você atrasou/negociou: ${b.name}.`, 'warn');renderAll()}
function refuseBill(id){const b=state.bills.find(x=>x.id===id);if(!b||b.status!=='Pendente')return;b.status='Recusado';state.score-=b.type==='banco'?35:10;state.rep-=b.type==='salario'?6:1;state.stress+=6;if(b.type==='imposto')createFiscalCase(b);if(b.type==='salario'){const e=state.employees.find(x=>x.id===b.meta.employeeId);if(e)createLaborCase(e)}if(b.type==='manutencao'){const v=state.ownedVehicles.find(x=>x.ownedId===b.meta.vehicleId);if(v){v.condition-=18;if(v.condition<20&&chance(.55)){addLog(`${v.name} deu PT após manutenção ignorada.`, 'bad');state.ownedVehicles=state.ownedVehicles.filter(x=>x.ownedId!==v.ownedId);if(state.currentVehicle===v.ownedId)state.currentVehicle=null}}}if(b.type==='moradia'&&state.housingMode==='rent'&&chance(.45)){state.housing=housingOptions()[0].id;addLog('Você perdeu a moradia alugada e voltou para opção simples.', 'bad')}addLog(`Você recusou pagar: ${b.name}.`, 'bad');renderAll()}
function openBranch(id){const b=BRANCHES.find(x=>x.id===id);if(!b)return;if(!state.ownedUpgrades.includes('filial'))return addLog('Você precisa comprar o upgrade Sistema de filiais.', 'bad');if(state.branches.some(x=>x.id===id))return addLog('Você já tem filial nesse estado.', 'warn');if(state.cash<b.cost)return addLog('Caixa insuficiente.', 'bad');state.cash-=b.cost;state.branches.push({...b});addLog(`Filial aberta em ${b.name}.`, 'good');renderAll()}
function netWorth(){const cars=state.ownedVehicles.reduce((s,v)=>s+v.price*(v.condition/100)*.75,0);const homes=state.ownedHomes.reduce((sum,id)=>{const h=housingOptions().find(x=>x.id===id);return sum+(h?h.buy*city().cost*.9:0)},0);const debt=state.loans.reduce((s,l)=>s+l.balance,0);return state.cash+cars+homes+state.lifetime*.04-debt}
function applyRoutine(){let worked=0,studied=0,sold=0,rest=0;['morning','afternoon','night'].forEach(slot=>{const k=state.routine[slot];const a=ROUTINE[k];state.energy=clamp(state.energy+a.energy,0,100);state.hunger=clamp(state.hunger+a.hunger,0,100);state.stress=clamp(state.stress+a.stress,0,100);state.motivation=clamp(state.motivation+a.motivation,0,100);if(k==='trabalhar')worked++;if(k==='estudar')studied++;if(k==='vender')sold++;if(['descansar','familia','dormir'].includes(k))rest++;if(k==='burocracia')state.fiscalRisk=clamp(state.fiscalRisk-1.5,0,100)});if(studied)addSkillXp(pick(SKILL_KEYS),studied*3);if(sold&&chance(.35*sold*city().demand)){generateContracts(sold);if(typeof scheduleNextContract==='function') scheduleNextContract();addLog('Sua propaganda trouxe novas propostas antes do prazo normal.', 'good')}}
function nextDay(){if(!state.started)return;state.day++;applyRoutine();state.hunger=clamp(state.hunger-rand(5,9),0,100);if(state.hunger<25){state.health=clamp(state.health-rand(.8,2.2),0,100);state.energy=clamp(state.energy-4,0,100);if(chance(.25))addLog('Você está sem comer direito. Saúde e energia caíram.', 'bad')}const h=home();state.energy=clamp(state.energy+6+h.energy/8-(state.stress/28),0,100);state.stress=clamp(state.stress+h.stress/10,0,100);state.contracts.forEach(c=>c.expires--);const expired=state.contracts.filter(c=>c.expires<=0);if(expired.length){expired.forEach(()=>pick(state.competitors).power+=.8);addLog(`${expired.length} proposta(s) expiraram e foram para concorrentes.`, 'warn')}state.contracts=state.contracts.filter(c=>c.expires>0);state.jobs.forEach(updateJobDay);const done=state.jobs.filter(j=>j.progress>=100||j.remaining<=0);done.forEach(finishJob);state.jobs=state.jobs.filter(j=>!done.includes(j));state.legalCases.forEach(updateLegalDay);processEmployeeTasks();if(state.candidates.length&&state.day>state.candidateExpiresDay){state.candidates=[];addLog('Os candidatos do mês sumiram.', 'warn')}if(state.contracts.length<5&&chance(.45*city().demand+state.branches.length*.05))generateContracts(1);if(state.day>30){state.day=1;state.month++;if(state.month>12){state.month=1;state.year++;state.age++}closeMonth()}renderAll()}
function closeMonth(){generateMonthlyBills();monthlyVehicleWear();refreshCandidates();refreshCarShop();if(typeof scheduleNextContract==='function') scheduleNextContract(3,7);state.recurringClients.slice().forEach(r=>{if(chance(r.churn+(state.health<45?.08:0))){addLog(`${r.client} cancelou o contrato recorrente.`, 'bad');state.recurringClients=state.recurringClients.filter(x=>x.id!==r.id)}else{r.months++;state.cash+=r.monthly;state.monthRevenue+=r.monthly;state.lifetime+=r.monthly;addLog(`Receita recorrente de ${r.client}: ${money(r.monthly)}.`, 'good')}});if(state.regime==='mei'&&state.lifetime>81000){addBill('imposto','Regularização por estourar limite do MEI',Math.max(1800,state.monthRevenue*.08),{});addLog('Alerta do contador: você estourou/chegou perto do limite do MEI. Migre para Simples.', 'warn')}checkMilestones();recalcBusinessLevel();showMonthSummary();state.monthRevenue=0;state.monthExpenses=0;state.foodSpent=0}
function showMonthSummary(){const pending=state.bills.filter(b=>b.status==='Pendente').reduce((s,b)=>s+b.amount,0);byId('monthBox').innerHTML=`<h2>Resumo do mês ${state.month}</h2><div class="grid2"><div class="card"><b>Receita</b><h2>${money(state.monthRevenue)}</h2></div><div class="card"><b>Despesas</b><h2>${money(state.monthExpenses)}</h2></div><div class="card"><b>Cobranças</b><h2>${money(pending)}</h2></div><div class="card"><b>Novidades</b><p>Loja, candidatos e contratos atualizados.</p></div></div><div class="actions-row"><button class="primary" onclick="currentTab='bills';closeModal('monthModal');renderAll()">Ir para cobranças</button><button onclick="closeModal('monthModal')">Continuar</button></div>`;openModal('monthModal')}
function checkMilestones(){MILESTONES.forEach(m=>{if(state.lifetime>=m&&!state.reached.includes(m)){state.reached.push(m);state.cash+=m<1000000?m*.03:0;state.score+=10;addLog(`Marco alcançado: ${money(m)} de faturamento total!`, 'good')}})}
function setRoutine(slot,val){state.routine[slot]=val;addLog(`Rotina atualizada: ${slot} = ${ROUTINE[val].name}.`, 'good');renderAll()}
function takeCourse(id){const c=COURSES.find(x=>x.id===id);if(!c)return;const cost=c.cost*city().cost;if(state.cash<cost)return addLog('Sem caixa para curso.', 'bad');if(state.energy<c.energy)return addLog('Sem energia para estudar.', 'warn');state.cash-=cost;state.energy-=c.energy;state.hunger=clamp(state.hunger-4,0,100);addSkillXp(c.skill,c.xp);addLog(`Curso concluído: ${c.name}.`, 'good');renderAll()}
function toggleAuto(){if(timer){clearInterval(timer);timer=null;byId('autoBtn').textContent='▶ Iniciar'}else{timer=setInterval(nextDay,speed);byId('autoBtn').textContent='⏸ Pausar'}}
function setSpeed(v){speed=Number(v);if(timer){clearInterval(timer);timer=setInterval(nextDay,speed)}}
function skipMonth(){const n=31-state.day;for(let i=0;i<n;i++)nextDay()}
function saveGame(){localStorage.setItem(SAVE_KEY,JSON.stringify(state));addLog('Jogo salvo.', 'good')}
function loadGame(){const raw=localStorage.getItem(SAVE_KEY);if(!raw)return addLog('Nenhum save encontrado.', 'warn');state=JSON.parse(raw);closeModal('startModal');addLog('Save carregado.', 'good');renderAll()}
function resetGame(){if(confirm('Resetar jogo e apagar save?')){localStorage.removeItem(SAVE_KEY);location.reload()}}
function dashboard(){const debt=state.loans.reduce((s,l)=>s+l.balance,0);return `<div class="section-title"><h2>📌 Painel</h2></div><div class="grid"><div class="card"><h4>Trabalhos em execução</h4>${state.jobs.length?state.jobs.map(jobMini).join(''):'<p class="muted">Nenhum trabalho ativo.</p>'}</div><div class="card"><h4>Empresa</h4><p>Nível: <b>${biz().name}</b></p><p class="muted">${biz().desc}</p><p>Regime: <b>${state.regime}</b></p><p>Dívida: <b>${money(debt)}</b></p><p>Patrimônio: <b>${money(netWorth())}</b></p></div><div class="card"><h4>Rotina de hoje</h4><p>Manhã: ${ROUTINE[state.routine.morning].name}</p><p>Tarde: ${ROUTINE[state.routine.afternoon].name}</p><p>Noite: ${ROUTINE[state.routine.night].name}</p></div><div class="card"><h4>Riscos</h4><p>Clientes: <b>${Math.round(state.clientRep)}</b></p><p>Fiscal: <b>${Math.round(state.fiscalRisk)}%</b></p><p>Processos ativos: <b>${state.legalCases.filter(c=>!['Acordo','Vencido','Encerrado','Perdido'].includes(c.status)).length}</b></p><p>Cobranças pendentes: <b>${state.bills.filter(b=>b.status==='Pendente').length}</b></p></div></div>`}
function jobMini(j){return `<div class="mini-card"><b>${j.service}</b><p>${j.client} · ${j.status}</p><div class="pills"><span class="pill">${Math.round(j.progress)}%</span><span class="pill">faltam ${j.remaining}d</span><span class="pill">${money(j.value)}</span></div><div class="meter"><i style="width:${j.progress}%"></i></div></div>`}
function routine(){const opts=Object.entries(ROUTINE).map(([k,a])=>`<option value="${k}">${a.name}</option>`).join('');const slotName={morning:'Manhã',afternoon:'Tarde',night:'Noite'};return `<div class="section-title"><h2>🗓️ Rotina diária</h2></div><p class="muted">Trabalhar acelera contratos, mas aumenta fome e estresse. Estudar sobe habilidades.</p><div class="grid">${['morning','afternoon','night'].map(s=>`<div class="card"><h4>${slotName[s]}</h4><select onchange="setRoutine('${s}',this.value)">${opts}</select><p class="muted">Atual: ${ROUTINE[state.routine[s]].name}</p></div>`).join('')}</div>`}
function contracts(){return `<div class="section-title"><h2>💼 Contratos</h2></div><div class="grid">${state.contracts.length?state.contracts.map(contractCard).join(''):'<p class="muted">Sem propostas.</p>'}</div><h3>Em execução</h3><div class="grid">${state.jobs.length?state.jobs.map(activeCard).join(''):'<p class="muted">Nada em execução.</p>'}</div>`}
function activeCard(j){return `<div class="card"><h4>${j.emoji} ${j.service}</h4><p>${j.client} · ${j.status}</p><div class="pills"><span class="pill">Progresso ${Math.round(j.progress)}%</span><span class="pill">Prazo ${j.remaining}d</span><span class="pill">Executor ${j.executor==='player'?'Você':(state.employees.find(e=>e.id===j.executor)?.name||'Funcionário')}</span></div><div class="meter"><i style="width:${j.progress}%"></i></div></div>`}
function recurring(){return `<div class="section-title"><h2>🔁 Clientes recorrentes</h2></div><div class="grid">${state.recurringClients.length?state.recurringClients.map(r=>`<div class="card"><h4>${r.client}</h4><p>${r.service}</p><div class="pills"><span class="pill">${money(r.monthly)}/mês</span><span class="pill">Qualidade ${r.quality}</span><span class="pill">Meses ${r.months}</span></div></div>`).join(''):'<p class="muted">Nenhum cliente recorrente ainda.</p>'}</div>`}
function status(){return `<div class="section-title"><h2>⭐ Status e habilidades</h2></div><p class="muted">Habilidades afetam qualidade, pagamento e risco de processo.</p>${SKILL_KEYS.map(k=>{const s=state.skills[k];return `<div class="skill-row"><b>${SKILL_NAMES[k]}</b><div class="skillbar"><i style="width:${s.xp}%"></i></div><span>Nv. ${s.level}</span></div>`}).join('')}`}
function courses(){return `<div class="section-title"><h2>🎓 Cursos</h2></div><div class="grid">${COURSES.map(c=>`<div class="card"><h4>${c.name}</h4><div class="pills"><span class="pill">${money(c.cost*city().cost)}</span><span class="pill">XP +${c.xp}</span><span class="pill">Energia -${c.energy}</span></div><button class="primary" onclick="takeCourse('${c.id}')">Fazer curso</button></div>`).join('')}</div>`}
function upgrades(){return `<div class="section-title"><h2>🌳 Upgrades</h2></div><div class="grid">${UPGRADES.map(u=>{const bought=state.ownedUpgrades.includes(u.id),can=u.req(state);return `<div class="card ${!can&&!bought?'locked':''}"><h4>${u.emoji} ${u.name} ${bought?'✅':''}</h4><p class="muted">${u.effect}</p><div class="pills"><span class="pill">${money(u.cost)}</span><span class="pill">${can?'Disponível':'Bloqueado'}</span></div><button class="primary" onclick="buyUpgrade('${u.id}')" ${bought?'disabled':''}>${bought?'Comprado':'Comprar'}</button></div>`}).join('')}</div>`}
function team(){return `<div class="section-title"><h2>👷 Equipe</h2><button onclick="refreshCandidates();renderAll()">Abrir seleção</button></div><p class="muted">Candidatos ficam 3 dias e mudam todo mês.</p><h3>Candidatos até dia ${state.candidateExpiresDay}</h3><div class="grid">${state.candidates.length?state.candidates.map(c=>`<div class="card"><h4>${c.name}, ${c.age} anos</h4><p>${c.label} · ${money(c.salary)}/mês</p><p class="muted">${c.personality} · experiência ${c.experience} ano(s)</p><button class="primary" onclick="interviewCandidate('${c.id}')">Mini entrevista</button></div>`).join(''):'<p class="muted">Nenhum candidato.</p>'}</div><h3>Funcionários</h3><div class="grid">${state.employees.length?state.employees.map(e=>`<div class="card"><h4>${e.name} · ${e.label}</h4><p>Salário ${money(e.salary)} · moral ${Math.round(e.morale)}% · tarefa: <b>${e.task}</b></p><div class="actions-row"><button onclick="setEmployeeTask('${e.id}','vender')">Vender</button><button onclick="setEmployeeTask('${e.id}','treinar')">Treinar</button><button onclick="setEmployeeTask('${e.id}','atender')">Atender</button><button onclick="setEmployeeTask('${e.id}','ocioso')">Ocioso</button><button class="danger" onclick="fireEmployee('${e.id}')">Demitir</button></div></div>`).join(''):'<p class="muted">Você trabalha sozinho.</p>'}</div>`}
function legal(){return `<div class="section-title"><h2>⚖️ Jurídico</h2></div><div class="grid">${state.legalCases.length?state.legalCases.map(c=>`<div class="card"><h4>${c.kind}: ${c.name}</h4><p>${c.reason}</p><div class="pills"><span class="pill">Pedido ${money(c.requested)}</span><span class="pill">Risco ${Math.round(c.risk*100)}%</span><span class="pill">${c.status}</span></div><div class="actions-row"><button class="warning" onclick="settleCase('${c.id}')">Acordo</button><button onclick="defendCase('${c.id}')">Recorrer</button><button class="danger" onclick="ignoreCase('${c.id}')">Ignorar</button></div></div>`).join(''):'<p class="muted">Nenhum processo ativo.</p>'}</div>`}
function bills(){return `<div class="section-title"><h2>🧾 Cobranças</h2></div><table class="table"><tr><th>Cobrança</th><th>Valor</th><th>Status</th><th>Ações</th></tr>${state.bills.map(b=>`<tr><td>${b.name}</td><td>${money(b.amount)}</td><td>${b.status}</td><td>${b.status==='Pendente'?`<button onclick="payBill('${b.id}')">Pagar</button> <button onclick="delayBill('${b.id}')">Atrasar</button> <button class="danger" onclick="refuseBill('${b.id}')">Recusar</button>`:'-'}</td></tr>`).join('')}</table>`}
function bank(){return `<div class="section-title"><h2>🏦 Banco</h2></div><div class="card"><div class="form-grid"><label>Valor desejado<input id="loanAmount" type="number" value="50000"></label><label>Parcelas<select id="loanMonths"><option>12</option><option>24</option><option>36</option><option>48</option><option>60</option></select></label><label>Finalidade<select id="loanPurpose"><option>capital de giro</option><option>comprar carro</option><option>empresa</option><option>quitar dívida</option><option>abrir filial</option></select></label></div><button class="primary" onclick="requestLoan()">Enviar para análise bancária</button></div><h3>Empréstimos ativos</h3><div class="grid">${state.loans.length?state.loans.map(l=>`<div class="card"><h4>${l.purpose}</h4><p>Saldo ${money(l.balance)} · ${l.monthsLeft} meses</p><p>Parcela ${money(l.payment)} · juros ${(l.rate*100).toFixed(2)}% a.m.</p></div>`).join(''):'<p class="muted">Nenhum empréstimo.</p>'}</div>`}
function calendar(){const events=[];state.jobs.forEach(j=>events.push({day:Math.max(1,state.day+j.remaining),text:`Entrega: ${j.service} para ${j.client}`,type:'contrato'}));state.bills.filter(b=>b.status==='Pendente').forEach(b=>events.push({day:state.day,text:`Cobrança: ${b.name}`,type:'cobrança'}));if(state.candidates.length)events.push({day:state.candidateExpiresDay,text:'Candidatos expiram',type:'equipe'});events.push({day:30,text:'Fechamento do mês',type:'mês'});return `<div class="section-title"><h2>📅 Agenda</h2></div><table class="table"><tr><th>Dia</th><th>Evento</th><th>Tipo</th></tr>${events.sort((a,b)=>a.day-b.day).map(e=>`<tr><td>${e.day}</td><td>${e.text}</td><td>${e.type}</td></tr>`).join('')}</table>`}
function food(){return `<div class="section-title"><h2>🍽️ Alimentação</h2></div><p class="muted">Se você não comer, fome cai e a saúde começa a descer.</p><div class="grid">${Object.entries(FOOD).map(([k,f])=>`<div class="card"><h4>${f.name}</h4><div class="pills"><span class="pill">${money(f.cost*city().cost)}</span><span class="pill">Fome +${f.hunger}</span><span class="pill">Energia ${f.energy}</span><span class="pill">Estresse ${f.stress}</span></div><button class="primary" onclick="eat('${k}')">Comprar</button></div>`).join('')}</div>`}
function housing(){return `<div class="section-title"><h2>🏠 Moradia em ${city().name}</h2></div><div class="grid">${housingOptions().map(h=>{const atual=state.housing===h.id,owned=state.ownedHomes.includes(h.id);return `<div class="card ${atual?'selected':''}"><div class="emoji">${h.emoji}</div><h4>${h.name} ${atual?'✅':''}</h4><div class="pills"><span class="pill">Aluguel ${money(h.rent*city().cost)}</span><span class="pill">Comprar ${money(h.buy*city().cost)}</span><span class="pill">Energia +${h.energy}</span><span class="pill">Status +${h.status}</span></div><div class="actions-row"><button onclick="rentHousing('${h.id}')">Alugar</button><button class="primary" onclick="buyHousing('${h.id}')">${owned?'Morar no imóvel':'Comprar'}</button>${owned?`<button class="warning" onclick="sellHousing('${h.id}')">Vender</button>`:''}</div></div>`}).join('')}</div>`}
function cars(){return `<div class="section-title"><h2>🚗 Loja de veículos do mês</h2><button onclick="refreshCarShop();renderAll()">Atualizar ofertas</button></div><p class="muted">A loja muda todo mês e mostra só algumas ofertas.</p><div class="grid">${state.carShop.map(v=>`<div class="card">${img(v.img,v.emoji)}<h4>${v.name}</h4><div class="pills"><span class="pill">Ano ${v.year}</span><span class="pill">Preço ${money(v.price)}</span><span class="pill">Condição ${Math.round(v.condition)}%</span><span class="pill">Manutenção ${money(v.maint)}/mês</span></div><button class="primary" onclick="buyVehicle('${v.offerId}')">Comprar</button></div>`).join('')}</div><h3>Meus veículos</h3><div class="grid">${state.ownedVehicles.length?state.ownedVehicles.map(v=>`<div class="card"><h4>${v.name}</h4><p>Condição ${Math.round(v.condition)}%</p><button onclick="state.currentVehicle='${v.ownedId}';renderAll()">Usar este</button></div>`).join(''):'<p class="muted">Nenhum veículo comprado.</p>'}</div>`}
function branches(){return `<div class="section-title"><h2>🗺️ Filiais</h2></div><div class="grid">${BRANCHES.map(b=>`<div class="card"><h4>${b.name} ${state.branches.some(x=>x.id===b.id)?'✅':''}</h4><p class="muted">${b.desc}</p><div class="pills"><span class="pill">Abertura ${money(b.cost)}</span><span class="pill">Mensal ${money(b.monthly)}</span></div><button class="primary" onclick="openBranch('${b.id}')">Abrir filial</button></div>`).join('')}</div>`}
function dre(){const debt=state.loans.reduce((s,l)=>s+l.balance,0);return `<div class="section-title"><h2>📊 DRE e balanço</h2></div><div class="grid"><div class="card"><h4>DRE do mês</h4><p>Receita: <b>${money(state.monthRevenue)}</b></p><p>Despesas: <b>${money(state.monthExpenses)}</b></p><p>Resultado: <b>${money(state.monthRevenue-state.monthExpenses)}</b></p></div><div class="card"><h4>Balanço</h4><p>Caixa: <b>${money(state.cash)}</b></p><p>Dívidas: <b>${money(debt)}</b></p><p>Patrimônio estimado: <b>${money(netWorth())}</b></p></div></div>`}
initSelects();state=defaultState();renderAll();
