/* CEO Brasil v22 - mais divertida e guiada */
(function(){
  const QUICK_JOBS=[
    {id:'banner',name:'Criar banner simples',emoji:'🖼️',pay:[90,180],energy:8,hunger:5,skill:'design',xp:7,desc:'Bico rápido para levantar caixa.'},
    {id:'suporte',name:'Suporte local no bairro',emoji:'🛠️',pay:[130,280],energy:12,hunger:7,skill:'atendimento',xp:8,desc:'Configurar e-mail, impressora, Wi-Fi ou computador.'},
    {id:'ajuste',name:'Ajuste pequeno em site',emoji:'💻',pay:[180,420],energy:14,hunger:8,skill:'programacao',xp:9,desc:'Correção pequena em site.'},
    {id:'panfleto',name:'Entregar panfleto',emoji:'📄',pay:[80,160],energy:18,hunger:10,skill:'vendas',xp:6,desc:'Ganha pouco, mas salva a comida.'},
    {id:'story',name:'Arte rápida para story',emoji:'🎨',pay:[100,230],energy:9,hunger:5,skill:'marketing',xp:7,desc:'Treina design/marketing no começo.'}
  ];
  const TIPS=['Aceite contratos fáceis no começo. Médio e difícil exigem habilidade/equipe.','Coma antes de pular dias. Fome baixa derruba saúde e qualidade.','Não compre carro caro cedo: seguro e manutenção quebram o caixa.','Se atrasar, seja sincero com cliente. Prometer e não cumprir sai caro.','Bicos salvam o começo, mas clientes recorrentes sustentam a empresa.','Estudar melhora habilidades e libera contratos maiores.'];
  const STORY={1:'Você ainda trabalha de casa e precisa sobreviver ao primeiro mês.',2:'Agora é hora de formalizar e parecer profissional.',3:'Você começou a respirar. Monte equipe e vire agência pequena.',4:'Clientes maiores exigem processo, contador e atendimento.',5:'A empresa pode abrir filial e sair da cidade inicial.',6:'Agora o desafio é escala, equipe e contratos nacionais.',7:'Você virou magnata. O objetivo é manter o império.'};
  function ensure(){if(!state)return;state.quickJobsToday=state.quickJobsToday||0;state.quickJobDay=state.quickJobDay||key();state.tutorialFlags=state.tutorialFlags||{};state.positiveEvents=state.positiveEvents||[];}
  function key(){return `${state.year||1}-${state.month||1}-${state.day||1}`}
  function addTab(id,label,after){try{if(!TABS.some(t=>t[0]===id)){const i=TABS.findIndex(t=>t[0]===after);TABS.splice(i>=0?i+1:TABS.length-1,0,[id,label])}}catch(e){}}
  function comp(c){const d=+c.diff||1;if(c.complexity==='easy'||d<=1.25)return{key:'easy',label:'Fácil',color:'good'};if(c.complexity==='medium'||d<=2.25)return{key:'medium',label:'Médio',color:'warn'};return{key:'hard',label:'Difícil',color:'bad'}}
  function est(c,executor='player'){let skill=1;try{skill=weightedSkill(c,executor)}catch(e){}const ratio=skill/Math.max(.8,c.diff||1);let daily=(100/Math.max(1,c.days||1))*(.72+ratio*.48);const ck=comp(c).key;if(ck==='easy')daily*=1.18;if(ck==='hard')daily*=.82;if(executor==='player'){if(state.energy<35)daily*=.78;if(state.hunger<35)daily*=.82;if(state.health<45)daily*=.82;if(state.stress>75)daily*=.84}if((state.ownedUpgrades||[]).includes('notebook'))daily*=1.10;if((state.ownedUpgrades||[]).includes('internet'))daily*=1.06;const days=Math.max(1,Math.ceil(100/Math.max(8,daily)));let chancePct=clamp(100-Math.max(0,days-(c.days||1))*16+Math.max(0,(c.days||1)-days)*5,8,98);if(ck==='easy')chancePct=Math.max(chancePct,58);return{days,chancePct:Math.round(chancePct)}}
  function alerts(){const a=[];if(state.hunger<30)a.push('Fome baixa: compre comida antes de pular dias.');if(state.health<45)a.push('Saúde baixa: descanse, coma melhor ou vá ao hospital.');if((state.jobs||[]).some(j=>(j.remaining||0)<0))a.push('Contrato atrasado: fale com o cliente ou finalize rápido.');if((state.bills||[]).some(b=>b.status==='Pendente'))a.push('Cobranças pendentes podem virar multa, despejo ou processo.');if((state.legalCases||[]).some(c=>!['Acordo pago','Vencido','Encerrado','Perdido'].includes(c.status)))a.push('Existe processo/notificação ativa. Resolver cedo costuma sair mais barato.');return a}
  function chapter(){const l=state.lifetime||0;if(l>=1e9)return 7;if(l>=1e7)return 6;if(l>=1e6)return 5;if(l>=5e5)return 4;if(l>=1e5)return 3;if(l>=1e4)return 2;return 1}
  function tip(){if(state.hunger<30)return 'Você está com fome. Compre comida antes de aceitar mais contrato.';if((state.jobs||[]).some(j=>(j.remaining||0)<0))return 'Você tem contrato atrasado. Negocie prazo antes de prometer.';if(state.cash<500)return 'Caixa baixo: faça bicos rápidos ou pegue contrato fácil.';if((state.contracts||[]).length===0)return 'Sem propostas? Espere 3 a 7 dias, faça propaganda ou coloque alguém para vender.';if((state.completed||0)<3)return 'Complete contratos fáceis para subir habilidade e reputação.';return pick(TIPS)}
  function score(){return Math.max(0,Math.round((netWorth()/900)+(state.lifetime/1800)+((state.rep||0)*85)+((state.clientRep||0)*60)+(state.completed||0)*120))}
  function scoreText(){return `CEO Brasil v22\nEmpresa: ${state.company}\nCidade: ${city().name}\nPatrimônio: ${money(netWorth())}\nFaturamento: ${money(state.lifetime)}\nContratos: ${state.completed||0}\nReputação: ${Math.round(state.rep||0)}\nMeses vivos: ${((state.year||1)-1)*12+(state.month||1)-1}\nPontuação: ${score()}`}
  window.copyRanking=async function(){const txt=scoreText();try{await navigator.clipboard.writeText(txt);addLog('Pontuação copiada para compartilhar.', 'good')}catch(e){prompt('Copie sua pontuação:',txt)}};
  window.showOnboarding=function(step=1){const steps=[['Bem-vindo','Você começa na periferia com R$ 5.000. Sobreviva, coma, pague contas e cresça.'],['Comida','Compre comida na aba Alimentação. Fome baixa derruba saúde e qualidade.'],['Contratos','Aceite contratos fáceis primeiro. O card mostra chance e tempo estimado.'],['Rotina','Trabalhar acelera contratos; estudar sobe habilidade; descansar protege saúde.'],['Dinheiro','Pague cobranças importantes. Atrasar pode virar multa, despejo ou processo.'],['Crescimento','Complete objetivos, ganhe recompensas e use bicos quando faltar caixa.']];const i=Math.max(0,Math.min(step-1,steps.length-1));const [t,tx]=steps[i];byId('alertsBox').innerHTML=`<h2>🧭 ${t}</h2><p>${tx}</p><div class="chapter-progress"><i style="width:${Math.round(step/steps.length*100)}%"></i></div><p class="muted">Passo ${step}/${steps.length}</p><div class="actions-row">${step<steps.length?`<button class="primary" onclick="showOnboarding(${step+1})">Próximo</button>`:`<button class="primary" onclick="closeModal('alertsModal')">Começar</button>`}<button onclick="closeModal('alertsModal')">Pular</button></div>`;openModal('alertsModal')};
  window.guia=function(){ensure();const al=alerts();return `<div class="section-title"><h2>🧭 Guia rápido</h2><button class="primary" onclick="showOnboarding(1)">Tutorial guiado</button></div><div class="grid2"><div class="card mentor-card"><h3>🧑‍🏫 Mentor</h3><p>${tip()}</p><button onclick="showMentorTip()">Nova dica</button></div><div class="card"><h3>O que fazer agora?</h3><ol><li>Coma se a fome estiver baixa.</li><li>Aceite contrato fácil com boa chance.</li><li>Faça bicos se estiver sem caixa.</li><li>Pague cobranças importantes.</li><li>Estude para liberar serviços maiores.</li></ol></div></div>${al.length?`<div class="card alert-card"><h3>⚠️ Alertas atuais</h3>${al.map(x=>`<div class="event warn">${x}</div>`).join('')}</div>`:''}<div class="card"><h3>Regra de ouro</h3><p class="muted">Contrato difícil sem habilidade + fome + estresse = atraso, desconto e cliente irritado.</p></div>`};
  window.showMentorTip=function(){byId('alertsBox').innerHTML=`<h2>🧑‍🏫 Mentor</h2><div class="card"><p>${tip()}</p></div><div class="actions-row"><button class="primary" onclick="closeModal('alertsModal')">Entendi</button><button onclick="showMentorTip()">Outra dica</button></div>`;openModal('alertsModal')};
  window.bicos=function(){ensure();if(state.quickJobDay!==key()){state.quickJobDay=key();state.quickJobsToday=0}return `<div class="section-title"><h2>⚡ Bicos rápidos</h2></div><div class="card"><h3>Trabalho de sobrevivência</h3><p class="muted">Bicos pagam pouco, mas ajudam quando não chegou cliente novo. Limite: 3 por dia.</p><p>Hoje: <b>${state.quickJobsToday}/3</b></p></div><div class="grid">${QUICK_JOBS.map(j=>`<div class="card"><h4>${j.emoji} ${j.name}</h4><p class="muted">${j.desc}</p><div class="pills"><span class="pill">${money(j.pay[0])} a ${money(j.pay[1])}</span><span class="pill">Energia -${j.energy}</span><span class="pill">Fome -${j.hunger}</span><span class="pill">XP ${SKILL_NAMES[j.skill]||j.skill}</span></div><button class="primary wide" onclick="doQuickJob('${j.id}')">Fazer bico</button></div>`).join('')}</div>`};
  window.doQuickJob=function(id){ensure();if(state.quickJobDay!==key()){state.quickJobDay=key();state.quickJobsToday=0}const j=QUICK_JOBS.find(x=>x.id===id);if(!j)return;if(state.quickJobsToday>=3)return addLog('Você já fez 3 bicos hoje.', 'warn');if(state.energy<j.energy)return addLog('Energia insuficiente para esse bico.', 'bad');if(state.hunger<j.hunger)return addLog('Você está com fome demais para esse bico.', 'bad');const gain=Math.round(rand(j.pay[0],j.pay[1])*city().demand);state.cash+=gain;state.monthRevenue+=gain;state.lifetime+=gain;state.energy=clamp(state.energy-j.energy,0,100);state.hunger=clamp(state.hunger-j.hunger,0,100);state.quickJobsToday++;try{addSkillXp(j.skill,j.xp)}catch(e){}addLog(`Bico concluído: ${j.name}. Você ganhou ${money(gain)}.`, 'good');if(typeof checkMissionRewards==='function')checkMissionRewards();renderAll()};
  const oldFood=window.food;window.food=function(){return (oldFood?oldFood():'')+`<div class="card"><h3>🍲 Dica de alimentação</h3><p class="muted">Marmita é barata; mercado é custo-benefício; restaurante reduz estresse; iFood economiza energia, mas pesa no bolso.</p></div>`};
  const oldCard=window.contractCard;window.contractCard=function(c){const base=oldCard?oldCard(c):`<div class="card"><h4>${c.service}</h4></div>`;const e=est(c,'player'),co=comp(c);const risk=e.chancePct>=80?'Baixo':e.chancePct>=55?'Médio':'Alto';const urgent=c.urgent?'<span class="pill bad">URGENTE</span>':'';const insert=`<div class="contract-estimate"><div class="pills"><span class="pill ${co.color}">Dificuldade: ${co.label}</span><span class="pill">Chance de cumprir: ${e.chancePct}%</span><span class="pill">Tempo estimado: ${e.days}d</span><span class="pill ${risk==='Alto'?'bad':risk==='Médio'?'warn':'good'}">Risco: ${risk}</span>${urgent}</div><p class="muted small">Se o tempo estimado for maior que o prazo, negocie ou delegue.</p></div>`;return base.replace('<div class="form-grid">',insert+'<div class="form-grid">')};
  const oldGen=window.generateContracts;window.generateContracts=function(n=2){const before=(state.contracts||[]).length;oldGen(n);(state.contracts||[]).slice(before).forEach(c=>{const ck=comp(c).key;if(ck!=='hard'&&chance(.13)){c.urgent=true;c.value=Math.round(c.value*rand(1.25,1.55));c.days=Math.max(1,Math.floor(c.days*.65));c.expires=Math.max(2,Math.min(c.expires||5,4));c.risk=(c.risk||.08)*1.15}})};
  const oldRanking=window.ranking;window.ranking=function(){return (oldRanking?oldRanking():'<div class="section-title"><h2>🏆 Ranking</h2></div>')+`<div class="card"><h3>Compartilhar com amigos</h3><pre class="scorebox">${scoreText()}</pre><button class="primary" onclick="copyRanking()">Copiar pontuação</button></div>`};
  const oldObj=window.objectives;window.objectives=function(){return `<div class="card chapter-card"><h3>História do capítulo ${chapter()}</h3><p>${STORY[chapter()]}</p></div>`+(oldObj?oldObj():'')};
  function positive(){const ev=[()=>{const g=Math.round(rand(80,220));state.cash+=g;state.monthRevenue+=g;addLog(`Evento positivo: um vizinho indicou um bico e você ganhou ${money(g)}.`, 'good')},()=>{state.hunger=clamp(state.hunger+18,0,100);addLog('Evento positivo: sua família ajudou com comida hoje.', 'good')},()=>{state.stress=clamp(state.stress-8,0,100);state.motivation=clamp(state.motivation+5,0,100);addLog('Evento positivo: você descansou melhor e ganhou motivação.', 'good')},()=>{if((state.contracts||[]).length<5){generateContracts(1);addLog('Evento positivo: uma indicação trouxe nova proposta.', 'good')}}];pick(ev)()}
  const oldFinish=window.finishJob;window.finishJob=function(j){oldFinish(j);if((state.contracts||[]).length<6&&(j.remaining||0)>=0&&chance(.18+Math.max(0,(state.clientRep||50)-60)/300)){generateContracts(1);addLog(`${j.client} indicou um possível novo cliente.`, 'good')}};
  const oldNext=window.nextDay;window.nextDay=function(){oldNext();if(!state?.started||state.gameOver)return;ensure();if(state.quickJobDay!==key()){state.quickJobDay=key();state.quickJobsToday=0}if(chance(.08))positive();if(state.health<28&&chance(.18)){state.energy=clamp(state.energy-12,0,100);addLog('Saúde muito baixa: você perdeu rendimento hoje.', 'bad')}};
  const oldStart=window.startGame;window.startGame=function(){oldStart();ensure();if(!state.tutorialFlags.opened){state.tutorialFlags.opened=true;setTimeout(()=>showOnboarding(1),180)}};
  addTab('guia','🧭 Guia','dashboard');addTab('bicos','⚡ Bicos','contracts');
  const oldRender=window.renderContent;window.renderContent=function(){const map={dashboard:window.dashboard,guia:window.guia,objectives:window.objectives,alerts:window.alerts,routine:window.routine,marketing:window.marketing,contracts:window.contracts,bicos:window.bicos,clients:window.clients,recurring:window.recurring,status:window.status,courses:window.courses,upgrades:window.upgrades,team:window.team,legal:window.legal,bills:window.bills,bank:window.bank,calendar:window.calendar,food:window.food,housing:window.housing,cars:window.cars,insurance:window.insurance,branches:window.branches,dre:window.dre,ranking:window.ranking};const fn=map[currentTab]||window.dashboard;byId('content').innerHTML=typeof fn==='function'?fn():'<div class="card"><p>Tela indisponível.</p></div>'};
  const oldDash=window.dashboard;window.dashboard=function(){const al=alerts().slice(0,3);return `<div class="card mentor-card"><h3>🧑‍🏫 Mentor</h3><p>${tip()}</p><div class="actions-row"><button onclick="currentTab='guia';renderAll()">Guia</button><button onclick="currentTab='bicos';renderAll()">Fazer bico</button><button onclick="copyRanking()">Copiar pontuação</button></div></div>${al.length?`<div class="card alert-card"><h3>⚠️ Cuidado agora</h3>${al.map(x=>`<div class="event warn">${x}</div>`).join('')}</div>`:''}${oldDash?oldDash():''}`};
  document.addEventListener('DOMContentLoaded',()=>{const actions=document.querySelector('.right .actions');if(actions&&!document.getElementById('copyScoreBtn'))actions.insertAdjacentHTML('beforeend','<button id="copyScoreBtn" onclick="copyRanking()">Copiar score</button>')});
  window.V22={est,tip,scoreText};if(typeof renderAll==='function'&&window.state)renderAll();
})();
